driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - rvm::system
      - stoplight::default
    attributes:
      rvm:
        default_ruby: '1.9.3'
        rubies:
          - 1.9.3
